FROM python:3

RUN groupadd appgroup && useradd -g appgroup appuser

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the application into the container.
COPY . /app

RUN chown -R appuser:appgroup /app

USER appuser

# Install the application dependencies.
WORKDIR /app

ENV UV_SYSTEM_PYTHON=true
ENV UV_CACHE_DIR="/app/.cache/uv"

RUN uv sync --frozen --no-cache

# Run the application.
CMD ["uv", "run", "uvicorn", "src.starphone_api.main:app", "--port", "8000", "--host", "0.0.0.0", "--reload"]