"""user-product

Revision ID: 74b333c189c7
Revises: 7be266891568
Create Date: 2025-11-13 23:47:42.873788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '74b333c189c7'
down_revision: Union[str, Sequence[str], None] = '7be266891568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'user', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'product', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'updated_by_id')
    op.drop_column('product', 'created_by_id')
    # ### end Alembic commands ###
