"""user-product

Revision ID: c1ee46cf8706
Revises: 7be266891568
Create Date: 2025-11-17 21:18:02.481925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c1ee46cf8706'
down_revision: Union[str, Sequence[str], None] = '7be266891568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'product', 'user', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'updated_by')
    op.drop_column('product', 'created_by')
    # ### end Alembic commands ###
